@extends('layouts.app', ['title' => 'Material · '.$project->name])

@section('content')
<a href="{{ route('projects.dashboard', $project) }}" class="text-sm font-semibold text-orange-600">&larr; Dashboard proyek</a>
<div class="mt-5"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-orange-600">Material</p><h1 class="mt-2 text-3xl font-bold">Master material</h1></div>
<div class="mt-8 grid gap-6 lg:grid-cols-[1fr_1.8fr]">
<section class="border border-slate-200 bg-white p-5 shadow-sm">
<h2 class="mb-4 text-lg font-semibold">Daftar material</h2>
<form method="POST" action="{{ route('projects.materials.store', $project) }}" class="space-y-3">@csrf
<input name="material_name" required placeholder="Nama material" class="w-full border border-slate-300 px-3 py-2 text-sm">
<input name="unit" required placeholder="Satuan" class="w-full border border-slate-300 px-3 py-2 text-sm">
<input type="number" name="current_stock" step="0.01" placeholder="Stok awal" class="w-full border border-slate-300 px-3 py-2 text-sm">
<button class="w-full bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Simpan material</button>
</form>
<form method="GET" class="mt-8 flex gap-2"><input name="material_search" value="{{ request('material_search') }}" placeholder="Cari master material" class="min-w-0 flex-1 border border-slate-300 px-3 py-2 text-sm"><button class="bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Cari</button></form>
<div class="mt-4 divide-y divide-slate-100">@forelse ($materials as $item)
<div class="flex items-center justify-between gap-2 py-3 text-sm"><a href="{{ route('projects.materials', [$project, 'material_id' => $item->id, 'month' => $month]) }}" class="min-w-0 flex-1 {{ $material?->id === $item->id ? 'font-semibold text-orange-600' : '' }}">{{ $item->material_name }} <small class="text-slate-400">({{ $item->unit }})</small><strong class="ml-2">{{ $item->current_stock }}</strong></a>
<details><summary class="cursor-pointer text-orange-600">Edit</summary><form method="POST" action="{{ route('projects.materials.update', [$project, $item]) }}" class="mt-2 space-y-2">@csrf @method('PUT')<input name="material_name" value="{{ $item->material_name }}" required class="w-full border-slate-300 px-2 py-1 text-xs"><input name="unit" value="{{ $item->unit }}" required class="w-full border-slate-300 px-2 py-1 text-xs"><button class="bg-slate-900 px-2 py-1 text-xs text-white">Simpan</button></form><form method="POST" action="{{ route('projects.materials.destroy', [$project, $item]) }}" class="mt-2">@csrf @method('DELETE')<button class="text-xs text-red-600" onclick="return confirm('Hapus material ini?')">Hapus</button></form></details></div>
@empty <p class="py-4 text-sm text-slate-500">Belum ada material.</p> @endforelse</div>
</section>
<section class="border border-slate-200 bg-white p-5 shadow-sm">
<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">{{ $material?->material_name ?: 'Pilih material' }}</h2><p class="text-sm text-slate-500">Periode {{ $month }}</p></div><form method="GET" class="flex flex-wrap gap-2"><input type="hidden" name="material_id" value="{{ $material?->id }}"><select name="month" onchange="this.form.submit()" class="border-slate-300 px-2 py-2 text-sm">@foreach ($months as $availableMonth)<option value="{{ $availableMonth }}" @selected($month === $availableMonth)>{{ \Carbon\Carbon::createFromFormat('Y-m', $availableMonth)->format('F Y') }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" placeholder="Cari keperluan" class="w-36 border border-slate-300 px-3 py-2 text-sm"><button class="bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Filter</button></form></div>
@if ($material)
<form method="POST" action="{{ route('projects.materials.flows.store', $project) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="material_id" value="{{ $material->id }}"><input type="date" name="date" required class="border border-slate-300 px-3 py-2 text-sm"><input name="description" required placeholder="Keperluan" class="border border-slate-300 px-3 py-2 text-sm"><input type="number" name="in_qty" step="0.01" placeholder="Masuk" class="border border-slate-300 px-3 py-2 text-sm"><input type="number" name="out_qty" step="0.01" placeholder="Keluar" class="border border-slate-300 px-3 py-2 text-sm"><button class="bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white sm:col-span-2">Catat flow material</button></form>
<div class="mt-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-3 py-3">Tanggal</th><th class="px-3 py-3">Keperluan</th><th class="px-3 py-3">Masuk</th><th class="px-3 py-3">Keluar</th><th class="px-3 py-3">Balance</th><th class="px-3 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($flows as $flow)<tr><td class="px-3 py-3">{{ $flow->date->format('d M Y') }}</td><td class="px-3 py-3">{{ $flow->description }}</td><td class="px-3 py-3 text-emerald-600">{{ $flow->in_qty }}</td><td class="px-3 py-3 text-red-600">{{ $flow->out_qty }}</td><td class="px-3 py-3 font-semibold">{{ $flow->balance_qty }}</td><td class="px-3 py-3"><details><summary class="cursor-pointer text-orange-600">Edit</summary><form method="POST" action="{{ route('projects.materials.flows.update', [$project, $flow]) }}" class="mt-2 grid gap-2">@csrf @method('PUT')<input type="date" name="date" value="{{ $flow->date->format('Y-m-d') }}" required><input name="description" value="{{ $flow->description }}" required><input type="number" name="in_qty" value="{{ $flow->in_qty }}" step="0.01"><input type="number" name="out_qty" value="{{ $flow->out_qty }}" step="0.01"><button class="bg-slate-900 px-2 py-1 text-xs text-white">Simpan</button></form><form method="POST" action="{{ route('projects.materials.flows.destroy', [$project, $flow]) }}" class="mt-2">@csrf @method('DELETE')<button class="text-xs text-red-600" onclick="return confirm('Hapus transaksi ini?')">Hapus</button></form></details></td></tr>@empty<tr><td colspan="6" class="px-3 py-8 text-center text-sm text-slate-500">Tidak ada transaksi yang cocok.</td></tr>@endforelse</tbody></table></div>{{ $flows->links() }}
@endif
</section>
</div>
@endsection
