@extends('layouts.app', ['title' => 'Laporan Foto · '.$project->name])

@section('content')
<a href="{{ route('projects.dashboard', $project) }}" class="text-sm font-semibold text-orange-600">&larr; Dashboard proyek</a>
<div class="mt-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-orange-600">Dokumentasi proyek</p><h1 class="mt-2 text-3xl font-bold">Laporan foto pekerjaan</h1><p class="mt-2 text-slate-500">Tanggal terbaru ditampilkan lebih dulu.</p></div><form method="GET" class="flex items-center gap-2"><label for="photo-date" class="text-sm font-medium">Tanggal</label><select id="photo-date" name="date" onchange="this.form.submit()" class="border-slate-300 px-3 py-2 text-sm"><option value="">Semua tanggal</option>@foreach ($dates as $date)<option value="{{ $date->format('Y-m-d') }}" @selected($selectedDate === $date->format('Y-m-d'))>{{ $date->format('d M Y') }}</option>@endforeach</select></form></div>
<div class="mt-8 grid gap-6 lg:grid-cols-[1fr_2fr]">
    <section class="h-fit border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-semibold">Tambah laporan foto</h2><form method="POST" action="{{ route('projects.photos.store', $project) }}" enctype="multipart/form-data" class="space-y-4">@csrf<label class="block text-sm font-medium">Tanggal<input type="date" name="date" required value="{{ old('date', $selectedDate ?: now()->format('Y-m-d')) }}" class="mt-1 w-full border border-slate-300 px-3 py-2"></label><label class="block text-sm font-medium">Deskripsi<input name="description" required value="{{ old('description') }}" placeholder="Contoh: Pengecoran lantai dua" class="mt-1 w-full border border-slate-300 px-3 py-2"></label><label class="block text-sm font-medium">Foto pekerjaan<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required class="mt-1 w-full border-slate-300 px-3 py-2 text-sm"><small class="mt-1 block text-xs text-slate-500">Format JPG, PNG, atau WebP. Maksimal 25 MB.</small></label><button class="w-full bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-orange-700">Unggah laporan</button></form></section>
    <section><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-semibold">{{ $selectedDate ? 'Dokumentasi '.$selectedDate : 'Semua dokumentasi' }}</h2><span class="text-sm text-slate-500">{{ $reports->count() }} foto</span></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@forelse ($reports as $report)<article class="overflow-hidden border border-slate-200 bg-white shadow-sm"><button type="button" class="block w-full text-left" onclick="openPhoto('{{ $report->photo_path ? route('media.file', ['path' => $report->photo_path]) : '' }}', '{{ addslashes($report->description) }}')">@if ($report->photo_path)<img src="{{ route('media.file', ['path' => $report->photo_path]) }}" alt="{{ $report->description }}" class="h-48 w-full object-cover">@else<div class="flex h-48 items-center justify-center bg-slate-100 text-sm text-slate-400">Foto dummy belum diunggah</div>@endif<div class="p-4"><p class="text-xs text-orange-600">{{ $report->date->format('d M Y') }}</p><h3 class="mt-1 font-semibold">{{ $report->description }}</h3></div></button><details class="border-t border-slate-100 p-4"><summary class="cursor-pointer text-sm font-semibold text-slate-600">Edit laporan</summary><form method="POST" action="{{ route('projects.photos.update', [$project, $report]) }}" enctype="multipart/form-data" class="mt-3 space-y-3">@csrf @method('PUT')<input type="date" name="date" required value="{{ $report->date->format('Y-m-d') }}" class="w-full border-slate-300 px-2 py-1.5 text-sm"><input name="description" required value="{{ $report->description }}" class="w-full border-slate-300 px-2 py-1.5 text-sm"><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" class="w-full text-xs"><button class="w-full bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Simpan perubahan</button></form><form method="POST" action="{{ route('projects.photos.destroy', [$project, $report]) }}" class="mt-2">@csrf @method('DELETE')<button class="w-full text-xs font-semibold text-red-600" onclick="return confirm('Hapus laporan foto ini?')">Hapus</button></form></details></article>@empty<div class="border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500 sm:col-span-2 xl:col-span-3">Belum ada laporan foto pada tanggal ini.</div>@endforelse</div></section>
</div>
<div id="photo-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/80 p-6" onclick="closePhoto()"><div class="max-h-full max-w-5xl" onclick="event.stopPropagation()"><button type="button" onclick="closePhoto()" class="mb-3 float-right text-2xl text-white" aria-label="Tutup">&times;</button><img id="photo-preview" src="" alt="" class="max-h-[80vh] max-w-full object-contain"><p id="photo-caption" class="mt-3 text-center text-sm text-white"></p></div></div>
<script>function openPhoto(src, caption){if(!src)return;document.getElementById('photo-preview').src=src;document.getElementById('photo-preview').alt=caption;document.getElementById('photo-caption').textContent=caption;document.getElementById('photo-modal').classList.remove('hidden');document.getElementById('photo-modal').classList.add('flex')}function closePhoto(){document.getElementById('photo-modal').classList.add('hidden');document.getElementById('photo-modal').classList.remove('flex')}</script>
@endsection
