@extends('layouts.app', ['title' => 'Progress · '.$project->name])

@section('content')
<a href="{{ route('projects.dashboard', $project) }}" class="text-sm font-semibold text-orange-600">&larr; Dashboard proyek</a>
<div class="mt-5 flex items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-orange-600">Progress proyek</p><h1 class="mt-2 text-3xl font-bold">Kurva S & Lapjusik</h1></div></div>
<div class="progress-overview mt-8 grid gap-6 lg:grid-cols-[1.5fr_1fr]">
    <section class="progress-chart border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-semibold">Rencana vs aktual mingguan</h2><canvas id="progress-chart" height="150"></canvas></section>
    <section class="guest-mutation-section border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-semibold">Tambah target mingguan</h2><form method="POST" action="{{ route('projects.progress.planned', $project) }}" class="space-y-3">@csrf<label class="block text-xs font-semibold text-slate-500">Tanggal dalam minggu</label><input type="date" name="week_start" required class="w-full border border-slate-300 px-3 py-2 text-sm"><input type="number" name="planned_progress_pct" min="0" max="100" step="0.01" required placeholder="Target %" class="w-full border border-slate-300 px-3 py-2 text-sm"><button class="w-full bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-orange-600">Simpan target</button></form></section>
</div>
@if (! session('guest_mode', false))
<section class="guest-mutation-section mt-6 border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-semibold">Tambah progres mingguan</h2><form method="POST" action="{{ route('projects.progress.store', $project) }}" class="grid gap-3 sm:grid-cols-[1fr_1fr_auto]">@csrf<label class="text-sm font-medium">Tanggal dalam minggu<input type="date" name="week_start" required class="mt-1 w-full border border-slate-300 px-3 py-2 text-sm"></label><label class="text-sm font-medium">Progress %<input type="number" name="progress_pct" min="0" max="100" step="0.01" required placeholder="Progress %" class="mt-1 w-full border border-slate-300 px-3 py-2 text-sm"></label><button class="self-end bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-orange-700">Catat progres</button></form></section>
@endif
<div class="progress-tables mt-6 grid gap-6 lg:grid-cols-2">
<section class="overflow-hidden border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="text-lg font-semibold">Target Kurva S Mingguan</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Minggu</th><th class="px-5 py-3">Target</th><th class="action-column px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($planned as $plan)<tr><td class="px-5 py-3">{{ $plan->week_start->format('d M Y') }}</td><td class="px-5 py-3">{{ $plan->planned_progress_pct }}%</td><td class="action-column px-5 py-3"><details><summary class="cursor-pointer text-orange-600">Edit</summary><form method="POST" action="{{ route('projects.progress.planned.update', [$project, $plan]) }}" class="mt-2 flex flex-wrap gap-2">@csrf @method('PUT')<input type="date" name="week_start" value="{{ $plan->week_start->format('Y-m-d') }}" required><input type="number" name="planned_progress_pct" value="{{ $plan->planned_progress_pct }}" min="0" max="100" step="0.01" required><button class="bg-slate-900 px-2 py-1 text-xs text-white">Simpan</button></form><form method="POST" action="{{ route('projects.progress.planned.destroy', [$project, $plan]) }}" class="mt-2">@csrf @method('DELETE')<button class="text-xs text-red-600" onclick="return confirm('Hapus target ini?')">Hapus</button></form></details></td></tr>@endforeach</tbody></table></div></section>
<section class="overflow-hidden border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="text-lg font-semibold">Laporan kemajuan fisik mingguan</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Minggu</th><th class="px-5 py-3">Progress</th><th class="action-column px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($lapjusik as $item)<tr><td class="px-5 py-3">{{ $item->week_start->format('d M Y') }}</td><td class="px-5 py-3">{{ $item->progress_pct }}%</td><td class="action-column px-5 py-3"><details><summary class="cursor-pointer text-orange-600">Edit</summary><form method="POST" action="{{ route('projects.progress.update', [$project, $item]) }}" class="mt-2 grid gap-2">@csrf @method('PUT')<input type="date" name="week_start" value="{{ $item->week_start->format('Y-m-d') }}" required><input type="number" name="progress_pct" value="{{ $item->progress_pct }}" min="0" max="100" step="0.01" required><button class="bg-slate-900 px-2 py-1 text-xs text-white">Simpan</button></form><form method="POST" action="{{ route('projects.progress.destroy', [$project, $item]) }}" class="mt-2">@csrf @method('DELETE')<button class="text-xs text-red-600" onclick="return confirm('Hapus laporan ini?')">Hapus</button></form></details></td></tr>@endforeach</tbody></table></div></section>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>new Chart(document.getElementById('progress-chart'), {type:'line', data:{labels:@json($chartLabels), datasets:[{label:'Rencana', data:@json($chartPlanned), borderColor:'#f97316', borderWidth:2, pointRadius:3, tension:.3, spanGaps:true},{label:'Aktual', data:@json($chartActual), borderColor:'#0f172a', borderWidth:2, pointRadius:3, tension:.3, spanGaps:false}]}, options:{responsive:true, scales:{y:{min:0,max:100}}}});</script>
@endsection
